---
- name: Deploy App
  hosts: app
  become: true
  vars:
    deploy_user: ubuntu
    container_name: otus-reddit
    container_image: 123344555/otus-reddit:1.0

  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ container_image }}"
        source: pull

    - name: Create containers
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        state: started
        restart: true
        ports:
          - "9292:9292"
