version: '3.9'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
    env_file:
      - .env
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${HOST_PORT}:${PORT}/tcp
    networks:
      - front_net
    env_file:
      - .env
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
    env_file:
      - .env
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
    env_file:
      - .env

volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
      - subnet:  10.0.2.0/24
  back_net:
    ipam:
      config:
      - subnet:  10.0.1.0/24
